# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  app2unit = {
    pname = "app2unit";
    version = "656d10d41e6f487efbccbeeab3334c829c9cd127";
    src = fetchgit {
      url = "https://github.com/Vladimir-csp/app2unit";
      rev = "656d10d41e6f487efbccbeeab3334c829c9cd127";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6tUEmskH/0KyvgNraLCKxCfaNBNfdY8ZLqvQCaHO+b0=";
    };
    date = "2025-08-19";
  };
  catppuccin-fcitx5 = {
    pname = "catppuccin-fcitx5";
    version = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
    src = fetchgit {
      url = "https://github.com/catppuccin/fcitx5";
      rev = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ss0kW+ulvMhxeZKBrjQ7E5Cya+02eJrGsE4OLEkqKks=";
    };
    date = "2025-05-16";
  };
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "6f173d0873dd33c5653dee89a831af3e49db3e36";
    src = fetchgit {
      url = "https://github.com/rafaelmardojai/firefox-gnome-theme";
      rev = "6f173d0873dd33c5653dee89a831af3e49db3e36";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9veVYpPCwKNjIK5gOigl5nEUN6tmrSHXUv4bVZkRuOE=";
    };
    date = "2025-08-04";
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "63406a0e91f8a66b3d9ec564fce64d887b19eaf1";
    src = fetchgit {
      url = "https://github.com/black7375/Firefox-UI-Fix";
      rev = "63406a0e91f8a66b3d9ec564fce64d887b19eaf1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OpF4k2gFSdo4plnc9ffzKdOGEKVbzVozeq5aE9QYnVY=";
    };
    date = "2025-08-10";
  };
  fuzzmoji = {
    pname = "fuzzmoji";
    version = "af4baa86611f2dfbe66c845f1b7edb582efc6cb5";
    src = fetchgit {
      url = "https://codeberg.org/codingotaku/fuzzmoji";
      rev = "af4baa86611f2dfbe66c845f1b7edb582efc6cb5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M3Sv7OLpUO84A1yS/TobxHVrBbwgedX8wNq58ZuJhKM=";
    };
    date = "2025-07-06";
  };
  runapp = {
    pname = "runapp";
    version = "d20c20c5e80ac28deec1e500f4afb32387fe5a7e";
    src = fetchgit {
      url = "https://github.com/c4rlo/runapp";
      rev = "d20c20c5e80ac28deec1e500f4afb32387fe5a7e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-RSCjGKhkfbX9XYTyknjlJUBSWb4KRLIumpH0FIEpnnY=";
    };
    date = "2025-07-16";
  };
  san-francisco-fonts = {
    pname = "san-francisco-fonts";
    version = "5a8fc7d569fa2b4fb5fe9a63ad66e5cf9ae00eae";
    src = fetchgit {
      url = "https://github.com/oyezcubed/Apple-Fonts-San-Francisco-New-York";
      rev = "5a8fc7d569fa2b4fb5fe9a63ad66e5cf9ae00eae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NBvWqHMaieaCZffqNitnhn979Sl2bAkIwC5sWW24z7g=";
    };
    date = "2020-08-27";
  };
  san-francisco-pro = {
    pname = "san-francisco-pro";
    version = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
    src = fetchgit {
      url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts";
      rev = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mAXExj8n8gFHq19HfGy4UOJYKVGPYgarGd/04kUIqX4=";
    };
    date = "2021-06-22";
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "a6eefb0f239797957a1292b94c45894ba7a09269";
    src = fetchgit {
      url = "https://github.com/vinceliuice/WhiteSur-gtk-theme";
      rev = "a6eefb0f239797957a1292b94c45894ba7a09269";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VEFcqwkBDSOpu/5bAX24UVF2Ot5WWox/3WgS/TwHXCc=";
    };
    date = "2025-08-20";
  };
}
