# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  app2unit = {
    pname = "app2unit";
    version = "7b9672a2dc16bdfbe7b7b7c27043529ca3bcb6ae";
    src = fetchgit {
      url = "https://github.com/Vladimir-csp/app2unit";
      rev = "7b9672a2dc16bdfbe7b7b7c27043529ca3bcb6ae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8/H0M9bFppZE6JHm6seZq9X/u6HyPncvd2CUcnbptg0=";
    };
    date = "2025-05-10";
  };
  catppuccin-fcitx5 = {
    pname = "catppuccin-fcitx5";
    version = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
    src = fetchgit {
      url = "https://github.com/catppuccin/fcitx5";
      rev = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ss0kW+ulvMhxeZKBrjQ7E5Cya+02eJrGsE4OLEkqKks=";
    };
    date = "2025-05-16";
  };
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "1ca82b07be9ff99da4b26092a846101ad109ef05";
    src = fetchgit {
      url = "https://github.com/rafaelmardojai/firefox-gnome-theme";
      rev = "1ca82b07be9ff99da4b26092a846101ad109ef05";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-G1ZrQrQWRLA15kLFT9+Ycz2GK+FmXHUwEK8pXnKSyKk=";
    };
    date = "2025-05-22";
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "6f50e027c3ca8d1e3a6f67dc095b311f8bcb9438";
    src = fetchgit {
      url = "https://github.com/black7375/Firefox-UI-Fix";
      rev = "6f50e027c3ca8d1e3a6f67dc095b311f8bcb9438";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/AaUXbT9iZ2si1pp5CTGvGrTG/hj1fU3Ir/ZAijvscc=";
    };
    date = "2025-05-11";
  };
  fuzzmoji = {
    pname = "fuzzmoji";
    version = "525fe00c5ee444bbdde125ef766157415f76ebc9";
    src = fetchgit {
      url = "https://codeberg.org/codingotaku/fuzzmoji";
      rev = "525fe00c5ee444bbdde125ef766157415f76ebc9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hwedN5KJex242dQqrv93qYUUV4oAwhoH0ShNAr1H/30=";
    };
    date = "2025-05-24";
  };
  runapp = {
    pname = "runapp";
    version = "af4af9bcbb82a13d8b47acf37ba21ab4361ce53a";
    src = fetchgit {
      url = "https://github.com/c4rlo/runapp";
      rev = "af4af9bcbb82a13d8b47acf37ba21ab4361ce53a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Aj9UZ09M2zi7kEtdJROGrYlwBGbv7fMjQov98lMhp9c=";
    };
    date = "2024-11-26";
  };
  san-francisco-pro = {
    pname = "san-francisco-pro";
    version = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
    src = fetchgit {
      url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts";
      rev = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mAXExj8n8gFHq19HfGy4UOJYKVGPYgarGd/04kUIqX4=";
    };
    date = "2021-06-22";
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "1e0656208de123b6cfe6e3c25d7777cff3b7b4d7";
    src = fetchgit {
      url = "https://github.com/vinceliuice/WhiteSur-gtk-theme";
      rev = "1e0656208de123b6cfe6e3c25d7777cff3b7b4d7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+sPuqU8UQpxgI7fAVxvKsTWQKLEak92tiHojYNW/LS0=";
    };
    date = "2025-05-14";
  };
}
